#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ "$1" == "InstRpacks" ];then
        Rscript $DIR/modules/Kronos_scRT_Rpackages_installer.R

elif [ "$1" == "10xtoKronos" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos 10xtoKronos [options]
        Rscript $DIR/modules/10XtoKronos.R -h | grep -v 10XtoKronos
    else
        Rscript $DIR/modules/10XtoKronos.R "${@:2}"
    fi

elif  [ "$1" == "binning" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos binning [options]
        Rscript $DIR/modules/Kronos_binning.R -h | grep -v Kronos_binning
    else
       Rscript $DIR/modules/Kronos_binning.R "${@:2}"
    fi


elif [ "$1" == "RT" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos RT [options]
        Rscript $DIR/modules/Kronos_RT.R -h | grep -v Kronos_RT
    else
       Rscript $DIR/modules/Kronos_RT.R "${@:2}"
    fi

elif [ "$1" == "WhoIsWho" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos WhoIsWho [options]
        Rscript $DIR/modules/Kronos_whoswho.R -h | grep -v Kronos_whoswho.R
    else
       Rscript $DIR/modules/Kronos_whoswho.R "${@:2}"
    fi

elif [ "$1" == "CNV" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos CNV [options]
        Rscript $DIR/modules/Kronos_cnv.R -h | grep -v Kronos_cnv
    else
       Rscript $DIR/modules/Kronos_cnv.R "${@:2}"
    fi

elif [ "$1" == "diagnostic" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos diagnostic [options]
        Rscript $DIR/modules/Kronos_diagnostic.R -h | grep -v Kronos_diagnostic
    else
       Rscript $DIR/modules/Kronos_diagnostic.R "${@:2}"
    fi

elif [ "$1" == "fastqtoBAM" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos fastqtoBAM [options]
        Rscript $DIR/modules/Kronos_fastqtoBAM.R -h | grep -v Kronos_fastqtoBAM
    else
       Rscript $DIR/modules/Kronos_fastqtoBAM.R "${@:2}"
    fi

elif [ "$1" == "compare" ] && [ "$2" == "RT" ];then
    if test "$#" == 2 ; then
        echo Usage: Kronos compare RT [options]
        Rscript $DIR/modules/Kronos_compare_RT.R -h | grep -v Kronos_compare
    else
       Rscript $DIR/modules/Kronos_compare_RT.R "${@:3}"
    fi

elif [ "$1" == "annotate" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos Corr [options]
        Rscript $DIR/modules/Kronos_annotate.R -h | grep -v Kronos_annotate.R
    else
       Rscript $DIR/modules/Kronos_annotate.R "${@:2}"
    fi

elif [ "$1" == "compare" ] && [ "$2" == "TW" ];then
    if test "$#" == 2 ; then
        echo Usage: Kronos compare TW [options]
        Rscript $DIR/modules/Kronos_compare_TW.R -h | grep -v Kronos_compare
    else
       Rscript $DIR/modules/Kronos_compare_TW.R "${@:3}"
    fi

elif [ "$1" == "population" ] && [ "$2" == "RT" ];then
    if test "$#" == 2 ; then
        echo Usage: Kronos population RT [options]
        Rscript $DIR/modules/Kronos_population_RT.R -h | grep -v Kronos_population_RT
    else
       Rscript $DIR/modules/Kronos_population_RT.R "${@:3}"
    fi

elif [ "$1" == "scPlots" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos scPlots [options]
        Rscript $DIR/modules/Kronos_scPlots.R -h | grep -v Kronos_scPlots
    else
       Rscript $DIR/modules/Kronos_scPlots.R "${@:2}"
    fi

elif [ "$1" == "Corr" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos Corr [options]
        Rscript $DIR/modules/Kronos_Corr.R -h | grep -v Kronos_Corr.R
    else
       Rscript $DIR/modules/Kronos_Corr.R "${@:2}"
    fi
elif [ "$1" == "DRed" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos DRed [options]
        Rscript $DIR/modules/Kronos_DRed.R -h | grep -v Kronos_DRed.R
    else
       Rscript $DIR/modules/Kronos_DRed.R "${@:2}"
    fi
else

echo -e "\nProgram: Kronos (Tools for the single cell analysis of the replication timing program)\n
Usage: Kronos <command> [options]\n
commands:\n
\t InstRpacks \t\t Install all the required R packages
\t fastqtoBAM \t\t Trims and maps reads
\t binning\t\t Calculates mappability and gc content for bins to be used with Kronos CNV
\t CNV\t\t\t Calculates copy number variation
\t 10xtoKronos\t\t Converts 10X genomics files in a format that Kronos can use
\t WhoIsWho \t\t Manually assign cell cycle stage
\t diagnostic \t\t Plotting tools to identify appropriate tresholds for Kronos RT
\t RT \t\t\t Calculates scReplication profiles and scRT
\t Corr \t\t\t Calculates pairwise spearman correlation between multipe pseudo-bulk replication timing/ rescaled bulk RT files
\t compare RT \t\t Compares RT results from multiple experiments
\t annotate \t\t Annotates sc variability files for Kronos compare TW
\t compare TW \t\t Allowes to investigate variability using a categorical annotation of the genome (for example binding sites or genes of interest)
\t population RT \t\t Calcualtes population RT starting from single cell BAM files and Kronos diagnostic outputs
\t scPlots \t\t scRT plots
\t DRed \t\t\t Applies DRed to identify possible scRT or scCN clusters
"

fi
