#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ "$1" == "10xtoKronos" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos 10xtoKronos [options]
        Rscript $DIR/modules/10XtoKronos.R -h | grep -v 10XtoKronos
    else
        Rscript $DIR/modules/10XtoKronos.R "${@:2}"
    fi
    
elif  [ "$1" == "binning" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos binning [options]
        Rscript $DIR/modules/Kronos_binning.R -h | grep -v Kronos_binning
    else
       Rscript $DIR/modules/Kronos_binning.R "${@:2}"
    fi
    
    
elif [ "$1" == "RT" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos RT [options]
        Rscript $DIR/modules/Kronos_RT.R -h | grep -v Kronos_RT
    else
       Rscript $DIR/modules/Kronos_RT.R "${@:2}"
    fi
    
elif [ "$1" == "WhoIsWho" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos RT [options]
        Rscript $DIR/modules/Kronos_whoswho.R -h | grep -v Kronos_RT
    else
       Rscript $DIR/modules/Kronos_whoswho.R "${@:2}"
    fi

elif [ "$1" == "CNV" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos CNV [options]
        Rscript $DIR/modules/Kronos_cnv.R -h | grep -v Kronos_cnv
    else
       Rscript $DIR/modules/Kronos_cnv.R "${@:2}"
    fi

elif [ "$1" == "diagnostic" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos diagnostic [options]
        Rscript $DIR/modules/Kronos_diagnostic.R -h | grep -v Kronos_diagnostic
    else
       Rscript $DIR/modules/Kronos_diagnostic.R "${@:2}"
    fi

elif [ "$1" == "fastqtoBAM" ];then
    if test "$#" == 1 ; then
        echo Usage: Kronos fastqtoBAM [options]
        Rscript $DIR/modules/Kronos_fastqtoBAM.R -h | grep -v Kronos_fastqtoBAM
    else
       Rscript $DIR/modules/Kronos_fastqtoBAM.R "${@:2}"
    fi

elif [ "$1" == "compare" ] && [ "$2" == "RT" ];then
    if test "$#" == 2 ; then
        echo Usage: Kronos compare RT [options]
        Rscript $DIR/modules/Kronos_compare_RT.R -h | grep -v Kronos_compare
    else
       Rscript $DIR/modules/Kronos_compare_RT.R "${@:3}"
    fi

elif [ "$1" == "compare" ] && [ "$2" == "TW" ];then
    if test "$#" == 2 ; then
        echo Usage: Kronos compare TW [options]
        Rscript $DIR/modules/Kronos_compare_TW.R -h | grep -v Kronos_compare
    else
       Rscript $DIR/modules/Kronos_compare_TW.R "${@:3}"
    fi
else

echo -e "\nProgram: Kronos (Tools for the single cell analysis of the replication timing program)\n
Usage: Kronos <command> [options]\n
commands:\n
\t fastqtoBAM \t Trims and maps reads
\t binning    \t Calculates mappability and gc content for bins to be used with Kronos CNV
\t CNV        \t Calculates copy number variation 
\t 10xtoKronos\t Converts 10X genomics files in a format that Kronos can use
\t diagnostic \t Plotting tools to identify appropriate tresholds for Kronos RT
\t RT         \t Calculates scReplication profiles and scRT
\t compare RT    \t Compares RT results from multiple experiments
\t compare TW \t Compares variability from multiple experiments and/or over multiple regions

"

fi
